### ISSUE TITLE
please provide apk 

### ISSUE THREAD

**Issue by revuwa** [KonradIT/wearbttn#1]
Thanks for that app, I really like to check out, but there is no apk behind your APK link (https://github.com/KonradIT/wearbttn/blob/master/app/app-release.apk) and I doesn't have the option to get it over Google Play right now, so would you provide the apk file for people like me, please?

**Comment by KonradIT** [comment]
mmmm I'll push it

**Comment by revuwa** [comment]
Thanks in advance, I stay tuned...

**Comment by KonradIT** [comment]
link is active
